name: Deploy to Amazon ECS

on:
  pull_request:
    branches: [ "master" ]


permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: windows-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.401'  # replace with your .NET version
    - name: Build
      run: dotnet build --configuration Release


